events {
    worker_connections 1024;
}

http {
    upstream fraud_detection {
        server api1:8080;
        server api2:8080;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://fraud_detection;
        }
    }
}